s = input("\nEnter a string: ")
print("\nFirst character:", s[0])
print("\nLast character:", s[-1])
print("\nFirst three characters:", s[:3])
print("\nLast three characters:", s[-3:])
print("\nCharacters from index 2 to 5:", s[2:5])
print("\nCharacters from index 2 to the end:", s[2:])
print("\nCharacters from the start to index 5:", s[:5])
